name: "myDesignLab"
markdown: kramdown
kramdown:
  input: GFM
description: "Designing for Designers since 2013"
url: http://localhost:4000
safe: true
#paginate: 5
#paginate_path: "/news/page:num/"
permalink: /news/:year/:month/:day/:title/
gems:
  - jekyll-redirect-from
